### ISSUE TITLE
[feature] add augmented search alternative UI

### ISSUE THREAD

**Issue by sinedied** [Azure-Samples/azure-search-openai-javascript#11]
In addition to the regular Chat UI, implement an alternative "augmented search" UI: list results found from the vector search just like a regular search, with an additional top panel providing AI insights.

See example here: https://agreeable-glacier-072729003.3.azurestaticapps.net/?q=node+with+mongo

![Image](https://github.com/anfibiacreativa/azure-search-open-ai-javascript/assets/593151/c5075b86-e6d4-4855-84ec-9e4d85fe6ca6)

#### Tasks
- [ ] Add new backend API to provide the search results
- [ ] Add new backend API to provide the AI suggestions result
- [ ] Implement the UI in the frontend
- [ ] Nice to have: implement caching for the results (especially the AI suggestion part)
