### ISSUE TITLE
[feature] VS Code extension

### ISSUE THREAD

**Issue by sinedied** [Azure-Samples/azure-search-openai-javascript#12]
We could create a VS Code extension that integrate the UI directly in VS Code.
A use case for this would be for example to allow querying a project source code with external documentation directly. Adding the documentation and source code from the project directly or from GitHub should be supported if we go with that use case.

#### Tasks
- [ ] Create new package in the repo for the VS Code extension
- [ ] Integrate the web UI in the extension
- [ ] Add command to the extension to index documentation and source code from the local project (or github)
- [ ] Add backend API to add add documentation and source code from the project as embeddings
