### ISSUE TITLE
[sdk] migrate from openai sdk to azure openai sdk

### ISSUE THREAD

**Issue by sinedied** [Azure-Samples/azure-search-openai-javascript#22]
Currently for some use cases, the original openai SDK is used as in the Python sample.
For those use cases, we should migrate to the @azure/openai SDK where possible (that doesn't include Langchain ones).

SDK ref: https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/openai/openai/README.md

### Tasks (in `api` package)
- [ ] Update `src/plugins/openai.ts` service to use AOAI SDK instead of OAI SDK
- [ ] Update `src/lib/approcahes/approach-base.ts` to use the new SDK for the embeddings
- [ ] Update `src/lib/approches/ask-retrieve-then-read.ts` approach to use the new SDK for the chat completion
- [ ] Update `src/lib/approches/chat-read-retrieve-read.ts` approach to use the new SDK for the chat completion
