### ISSUE TITLE
[frontend] extract the chat component into a standalone web component

### ISSUE THREAD

**Issue by sinedied** [Azure-Samples/azure-search-openai-javascript#27]
We want this sample to be reusable as product directly by our customers.
As such, we want the Chat component of the web app to be refactored as a standalone web component that can be distributed in an NPM package.

#### Tasks
- [x] 1. create a new package for the web component
- [x] 2. extract and rewrite the existing Chat component into a [Lit](https://lit.dev/) web component
- [ ] 3. update the existing webapp to use the new web component, as an usage demo
- [x] 4. allow the web component to be configurable through options (for example, to specify the endpoint)
- [ ] 5. write documentation for the web component package to explain how to use and integrate it
