### ISSUE TITLE
[feature] add simpler alternative API using Azure OpenAI BYOD

### ISSUE THREAD

**Issue by sinedied** [Azure-Samples/azure-search-openai-javascript#28]
In the latest Azure OpenAI release, an experimental built-in connector to Cognitive Search was added.
Using this new feature, it would be interesting to create a simpler example, adapting the chat-read-retrieve-read approach in a simplified Azure Function.

See: https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/openai/openai/samples-dev/bringYourOwnData.ts

#### Tasks
- [ ] create a new package for the azure function project
- [ ] implement a simplified /chat API without all the overrides options support, only implementing the RRR approach using the new Azure OpenAI  SDK
- [ ] add toggle in webapp developer setting to allow switching between the regular API and this simplified Function API
- [ ] update AZD template to deploy the Azure Function
- [ ] add documentation, and explain on how this can be used standalone with just SWA and Chat web component (#27)
