### ISSUE TITLE
[backend] complete port of Ask-Read-Decompse-Ask approach

### ISSUE THREAD

**Issue by sinedied** [Azure-Samples/azure-search-openai-javascript#30]
The "Ask-Read-Decompose-Ask" approach of the Python sample cannot be ported as-is currently, as Langchain JS is missing the [ReAct/ReAct document store agents](https://python.langchain.com/docs/modules/agents/agent_types/react_docstore).

We already have a working Langchain example (#29), so there's no urgency to port this one.

### Tasks
- [ ] Port ReAct document store to Langchain JS
- [ ] Complete port of Ask-Read-Decompose-Ask approach
- [ ] Contribute back ReAct agent with a PR to Langchain JS

**Comment by pamelafox** [comment]
We deleted the 2 langchain-based approaches, btw.

**Comment by sinedied** [comment]
Thanks @pamelafox for the update!
