### ISSUE TITLE
[backend] swagger/openapi spec generation

### ISSUE THREAD

**Issue by sinedied** [Azure-Samples/azure-search-openai-javascript#35]
To have API schemas also allowing for TypeSpec integration, we want to have an OpenAPI schema for all our backend services (api/ingestion for now).

#### Tasks
- [x] integrate https://www.npmjs.com/package/@fastify/swagger in all services
- [x] update schemas with description and errors
- [x] add endpoint in all services for swagger UI
