### ISSUE TITLE
[backend] port the existing current python backend to Node.js

### ISSUE THREAD

**Issue by sinedied** [Azure-Samples/azure-search-openai-javascript#5]
The existing API should be conserved for compatibility with the frontend.

#### Tasks
- [x] Bootstrap the new Node.js project
- [x] Use langchain js to adapt the existing Python code to JS
- [x] Use Azure SDKs for Cognitive Search
- [x] Add [REST Client](https://aka.ms/vscode/rest-client) API file for testing/validation
