### ISSUE TITLE
[backend] add opentelemetry support

### ISSUE THREAD

**Issue by sinedied** [Azure-Samples/azure-search-openai-javascript#58]
#### Tasks
- [x] add option to support opentelemetry with Azure App Insights
- [x] configure opentelemetry in indexer service
- [x] configure opentelemetry in search service

**Comment by sinedied** [comment]
Current blocked because of https://github.com/Azure/azure-sdk-for-js/issues/27287

**Comment by sinedied** [comment]
Azure SDK issue has been fixed, but now blocked by https://github.com/fastify/fastify-cli/issues/671
